apiVersion: v1
kind: Secret
metadata:
  name: {{ .Name }}
type: {{.SecretType}}
data:
{{range $i,$v := .Data.Slices}}
{{if eq $i 0}}
  peermspadmincerts: {{$v}}
{{end}}
{{if eq $i 1}}
  peermspcacerts: {{$v}}
{{end}}
{{if eq $i 2}}
  peermspkeystore: {{$v}}
{{end}}
{{if eq $i 3}}
  peermspsigncerts: {{$v}}
{{end}}
{{if eq $i 4}}
  peermsptlscacerts: {{$v}}
{{end}}
{{if eq $i 5}}
  ca.crt: {{$v}}
{{end}}
{{if eq $i 6}}
  peerserverkey: {{$v}}
{{end}}
{{if eq $i 7}}
  peerservercrt: {{$v}}
{{end}}
{{end}}
  tls.key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCi0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0=
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
