apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{.Name}}
  name: {{.Name}}
spec:
  clusterIP: None
  ports:
  - port: 7051
    protocol: TCP
    targetPort: 7051
  selector:
    app: {{.Name}}
  type: ClusterIP
